### ISSUE TITLE
请问我这个错误是怎么回事，找了好久还是解决不了

### ISSUE THREAD

**Issue by gonggtao** [YIYIMZ/my_orc_keras_verification_code_identification#7]
2019-04-22 10:46:08.222826: W tensorflow/core/framework/op_kernel.cc:1401] OP_REQUIRES failed at ctc_loss_op.cc:168 : Invalid argument: Saw a non-null label (index >= num_classes - 1) following a null label, batch: 0 num_classes: 10 labels: 1
Traceback (most recent call last):
  File "E:/Python/HandChracterRecognition/HandChracterRecognition.py", line 97, in <module>
    train()
  File "E:/Python/HandChracterRecognition/HandChracterRecognition.py", line 91, in train
    verbose = 1)
  File "E:\Python Edition\lib\site-packages\keras\engine\training.py", line 1039, in fit
    validation_steps=validation_steps)
  File "E:\Python Edition\lib\site-packages\keras\engine\training_arrays.py", line 199, in fit_loop
    outs = f(ins_batch)
  File "E:\Python Edition\lib\site-packages\keras\backend\tensorflow_backend.py", line 2715, in __call__
    return self._call(inputs)
  File "E:\Python Edition\lib\site-packages\keras\backend\tensorflow_backend.py", line 2675, in _call
    fetched = self._callable_fn(*array_vals)
  File "E:\Python Edition\lib\site-packages\tensorflow\python\client\session.py", line 1439, in __call__
    run_metadata_ptr)
  File "E:\Python Edition\lib\site-packages\tensorflow\python\framework\errors_impl.py", line 528, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.InvalidArgumentError: Saw a non-null label (index >= num_classes - 1) following a null label, batch: 0 num_classes: 10 labels: 1
	 [[{{node ctc/CTCLoss}}]]

我使用的是lstm代码，用于识别数字验证码，因此char_set = '0123456789'，训练的图片是用四位数字验证码，求解决

**Comment by gonggtao** [comment]
@YIYIMZ 十分感谢，你写的ctc代码非常简洁明了，对我这个初学者帮助很大！

**Comment by un-human** [comment]
> @YIYIMZ 十分感谢，你写的ctc代码非常简洁明了，对我这个初学者帮助很大！



> 2019-04-22 10:46:08.222826: W tensorflow/core/framework/op_kernel.cc:1401] OP_REQUIRES failed at ctc_loss_op.cc:168 : Invalid argument: Saw a non-null label (index >= num_classes - 1) following a null label, batch: 0 num_classes: 10 labels: 1
> Traceback (most recent call last):
> File "E:/Python/HandChracterRecognition/HandChracterRecognition.py", line 97, in 
> train()
> File "E:/Python/HandChracterRecognition/HandChracterRecognition.py", line 91, in train
> verbose = 1)
> File "E:\Python Edition\lib\site-packages\keras\engine\training.py", line 1039, in fit
> validation_steps=validation_steps)
> File "E:\Python Edition\lib\site-packages\keras\engine\training_arrays.py", line 199, in fit_loop
> outs = f(ins_batch)
> File "E:\Python Edition\lib\site-packages\keras\backend\tensorflow_backend.py", line 2715, in **call**
> return self._call(inputs)
> File "E:\Python Edition\lib\site-packages\keras\backend\tensorflow_backend.py", line 2675, in _call
> fetched = self._callable_fn(*array_vals)
> File "E:\Python Edition\lib\site-packages\tensorflow\python\client\session.py", line 1439, in **call**
> run_metadata_ptr)
> File "E:\Python Edition\lib\site-packages\tensorflow\python\framework\errors_impl.py", line 528, in **exit**
> c_api.TF_GetCode(self.status.status))
> tensorflow.python.framework.errors_impl.InvalidArgumentError: Saw a non-null label (index >= num_classes - 1) following a null label, batch: 0 num_classes: 10 labels: 1
> [[{{node ctc/CTCLoss}}]]
> 
> 我使用的是lstm代码，用于识别数字验证码，因此char_set = '0123456789'，训练的图片是用四位数字验证码，求解决

你知道 主函数入口在哪麽？
